---
name: Perl-Critic-Moose
version: 0.999_001
author:
  - 'Elliot Shank <perl@galumph.com>'
abstract: 'Policies for Perl::Critic concerned with using Moose, the "post-modern" object system for Perl.'
license: perl
resources:
  MailingList: http://perlcritic.tigris.org/servlets/SummarizeList?listName=users
  Repository: http://perlcritic.tigris.org/svn/perlcritic/trunk/Perl-Critic-Moose/
  homepage: http://perlcritic.com
  license: http://dev.perl.org/licenses/
requires:
  Perl::Critic::Policy: 1.093_02
  Perl::Critic::Utils: 1.093_02
  Perl::Critic::Utils::PPI: 1.093_02
  Readonly: 0
  base: 0
  strict: 0
  version: 0
  warnings: 0
build_requires:
  Carp: 0
  English: 0
  Perl::Critic::TestUtils: 1.093_02
  strict: 0
  warnings: 0
dynamic_config: 0
provides:
  Perl::Critic::Moose:
    file: lib/Perl/Critic/Moose.pm
    version: 0.999_001
  Perl::Critic::Policy::Moose::RequireCleanNamespace:
    file: lib/Perl/Critic/Policy/Moose/RequireCleanNamespace.pm
    version: 0.999_001
  Perl::Critic::Policy::Moose::RequireMakeImmutable:
    file: lib/Perl/Critic/Policy/Moose/RequireMakeImmutable.pm
    version: 0.999_001
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
